### ISSUE TITLE
error in python manage.py syncdb --migrate

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/moocng#61]
```
    (moocng)[root@felipeurrego moocng]# python manage.py syncdb --migrate
    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/var/www/moocng/lib/python2.6/site-packages/Django-1.4.8-py2.6.egg/django/core/management/__init__.py", line 443, in execute_from_command_line
        utility.execute()
      File "/var/www/moocng/lib/python2.6/site-packages/Django-1.4.8-py2.6.egg/django/core/management/__init__.py", line 382, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/var/www/moocng/lib/python2.6/site-packages/Django-1.4.8-py2.6.egg/django/core/management/base.py", line 196, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/var/www/moocng/lib/python2.6/site-packages/Django-1.4.8-py2.6.egg/django/core/management/base.py", line 231, in execute
        self.validate()
      File "/var/www/moocng/lib/python2.6/site-packages/Django-1.4.8-py2.6.egg/django/core/management/base.py", line 266, in validate
        num_errors = get_validation_errors(s, app)
      File "/var/www/moocng/lib/python2.6/site-packages/Django-1.4.8-py2.6.egg/django/core/management/validation.py", line 30, in get_validation_errors
        for (app_name, error) in get_app_errors().items():
      File "/var/www/moocng/lib/python2.6/site-packages/Django-1.4.8-py2.6.egg/django/db/models/loading.py", line 158, in get_app_errors
        self._populate()
      File "/var/www/moocng/lib/python2.6/site-packages/Django-1.4.8-py2.6.egg/django/db/models/loading.py", line 64, in _populate
        self.load_app(app_name, True)
      File "/var/www/moocng/lib/python2.6/site-packages/Django-1.4.8-py2.6.egg/django/db/models/loading.py", line 88, in load_app
        models = import_module('.models', app_name)
      File "/var/www/moocng/lib/python2.6/site-packages/Django-1.4.8-py2.6.egg/django/utils/importlib.py", line 35, in import_module
        __import__(name)
      File "/var/www/moocng/moocng/moocng/courses/models.py", line 53, in <module>
        class Course(Sortable):
      File "/var/www/moocng/moocng/moocng/courses/models.py", line 88, in Course
        choices=get_media_content_types_choices())
      File "/var/www/moocng/moocng/moocng/media_contents/__init__.py", line 62, in get_media_content_types_choices
        for handler_dict in settings.MEDIA_CONTENT_TYPES:
      File "/var/www/moocng/lib/python2.6/site-packages/Django-1.4.8-py2.6.egg/django/utils/functional.py", line 185, in inner
        return func(self._wrapped, *args)
    AttributeError: 'Settings' object has no attribute 'MEDIA_CONTENT_TYPES'
```

**Comment by johnfelipe** [comment]
fixed.
